version: "3.8"

x-logging: &default-logging
    options:
        max-size: "20m"
        max-file: "3"
    driver: json-file


services:
    gha:
        container_name: gh-actions-fil
        image: golang:1.21.7-bullseye
        entrypoint: ["/bin/bash -c 'sleep 10000000000'"]
        restart: unless-stopped
        logging: *default-logging
  
