name: "Main"
on:
    push:
        branches:
            - dummy-feat
    pull_request:
        branches:
            - master

jobs:
    dep-install:
        name: "Run dependency install"
        timeout-minutes: 30
        runs-on: ubuntu 
        steps:
            # - name: Install node
            #   uses: actions/setup-node@v2
            #   with:
            #       node-version: "20.0.0"

            # - name: Install yarn
            #   run: npm install -g yarn

            - name: Checkout repo
              uses: actions/checkout@main
              with:
                  submodules: "true"

            - name: Install other dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get -y install hwloc jq pkg-config bzr ocl-icd-opencl-dev
                  sudo apt install zsh -y
                  make install_solc_linux
                  # yarn install
                  sudo echo /usr/lib/aarch64-linux-gnu/libhwloc.so.15 | xargs -I {} sudo ln -s {} /usr/lib/libhwloc.so
                  sudo ln -s /usr/lib/aarch64-linux-gnu/libOpenCL.so /usr/lib/libOpenCL.so

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true

            # - name: Restore crates
            #   uses: actions/cache@v3
            #   with:
            #       path: |
            #           ~/.cargo/bin/
            #           ~/.cargo/registry/index/
            #           ~/.cargo/registry/cache/
            #           ~/.cargo/git/db/
            #       key: ${{ runner.os }}-cargo-${{ hashFiles('./testing/Cargo.lock') }}

    # smoke-tests:
    #     name: "Run smoke tests"
    #     timeout-minutes: 30
    #     runs-on: ubuntu 
    #     needs: [dep-install]
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v2
    #           with:
    #               submodules: "true"

    #         - name: Compile contracts
    #           run: ./testing/smoke_tests.sh

    miner-integration:
        name: "Miner API: integration tests"
        timeout-minutes: 30
        runs-on: ubuntu 
        needs: [dep-install]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: "true"

            - name: Run miner test
              run: |
                  cd testing
                  rustup target add wasm32-unknown-unknown
                  cargo test account_test
